var requirejs = require('requirejs');
requirejs.config({
	baseUrl: 'public/javascripts', 
	nodeRequire: require
}); 
 
requirejs(['app/card', 'app/rank'], function(Card, Rank){  
	exports['Card be be generated by jod'] = function(test){
		var card = Card.heart(Rank.TWO);    
		var another = Card.fjod(card.jod());  
		test.ok(another.equals(card));
		test.done();
	};
});